### ISSUE TITLE
lit-apollo vs. vanilla apollo-client

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [bennypowers/lit-apollo#19]
Since, lit-apollo is [not providing _web components per se_](https://github.com/bennypowers/lit-apollo/issues/2#issuecomment-392841780) (it is non-visual, so it doesn't use HTML Templates API and Shadow DOM API, some users [won't like to use custom elements for queries](https://github.com/bennypowers/lit-apollo/issues/11#issuecomment-407415306) (there is an extra performance cost for registering web component as an HTML element, DOM declaration and data binding; every property does come at a cost (observers, listeners, etc.) that are not necessary for working non-visual elements), so it doesn't use Custom Elements API), this is just a set of base classes, that's what I think about:

1. Why is it needed at all? What problem does it solve? What are the advantages compared to vanilla apollo-client?

2. Since it does not come as a set of web components, why it extends from lit-element (lit-element is intended to create custom elements rendered with lit-html, apollo-client has nothing to do with lit-html)? What if users want to extend e.g. [hyperhtml-element](https://github.com/WebReflection/hyperHTML-Element) by @WebReflection instead of lit-element?

3. Since it is just a set of base classes and ApolloClient [is also a class](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/ApolloClient.ts#L60), why not just extend it?

@bennypowers Could you please cover some advantages of lit-apollo over using vanilla apollo-client with lit-element (small code samples) in README?

**Comment by bennypowers** [comment]
Hey Alexei. Those are some good questions, and it's part of the reason we're working on adding mixins in #18 so you can use whichever custom element base class you like. Take a look, maybe try the branch out, let me know how it works for you.

As to why you'd use lit-apollo instead of just setting properties or something with apollo client methods, would be if you want to use a reactive component model in your app.

The ApolloClient constructor isn't a customElement base class.

Closing now, feel free to reopen if you have more questions.

**Comment by FluorescentHallucinogen** [comment]
@bennypowers What do you mean by "reactive component model"? The fact that when the `variables` or `query` property changes, the query gets automatically re-fetched?

**Comment by bennypowers** [comment]
That's right, I mean components which update the display when their state changes
